template = ""
rev_id = 74
template_sha = "bdfb17f42e2c70deceee0362bc3db1bec5090f22"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-nob-x-toy"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokmål"
__UND__ = "nob"
